### ISSUE TITLE
Feat: Add support for Terraform?

### ISSUE THREAD

**Issue by dannysteenman** [dannysteenman/vscode-iam-actions-snippets#1]
Would anybody be interested in that?

**Comment by ValAug** [comment]
Here are the features I anticipated to work, but they did not. I have included the code example used for testing. I am happy to support the Terraform aspect if possible.

Features:
Auto-completion: Provides intelligent auto-completion for IAM actions as you type.
Documentation Links: Quick access to AWS documentation for each IAM action directly from the snippet.
Smart Hover Information: When hovering over wildcard actions, displays all matching IAM actions, providing a comprehensive view of the permissions covered.

#---examplecode---

resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"

  # Terraform's "jsonencode" function converts a
  # Terraform expression result to valid JSON syntax.
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = [
          "ec2:Describe*",
          "ec2:"
          
        ]
        Effect   = "Allow"
        Resource = "*"
      },
    ]
  })
}

<img width="469" alt="terraformexample" src="https://github.com/user-attachments/assets/c12bf202-d84a-4ebd-ad30-fcad14a9269e">

**Comment by dannysteenman** [comment]
it should work now: https://github.com/dannysteenman/vscode-iam-actions-snippets/commit/87a2bceadc08c4e287dcf48699cd32d979d7017e

Please update the extension to v1.8.0

**Comment by charisad** [comment]
Awesome Thanks

**Comment by charisad** [comment]
Awesome thanks
